package com.bebetos.shoppinglist.dto.response;


public enum Message {

    // Exception Error
    EXCEPTION_MESSAGE_ERROR("EXCEPTION_MESSAGE_ERROR"),
    
    // User section
    USER_REGISTERED("USER_REGISTERED"),
    USER_ALREADY_REGISTERED("USER_ALREADY_REGISTERED"),
    USER_CREATION_ERROR("USER_CREATION_ERROR"),
    USER_CREATION_SUCCESS("USER_CREATION_SUCCESS"),
    USER_NOT_FOUND("USER_NOT_FOUND"),
    USER_WRONG_PASSWORD("USER_WRONG_PASSWORD"),
    USER_UNAUTHORIZED("USER_UNAUTHORIZED"),

    // Password section
    PASSWORD_WRONG_OLD("PASSWORD_WRONG_OLD"),
    PASSWORD_CHANGE_SUCCESS("PASSWORD_CHANGE_SUCCESS"),
    PASSWORD_CHANGE_ERROR("PASSWORD_CHANGE_ERROR"),
    PASSWORD_RECOVER_SUCCESS("PASSWORD_RECOVER_SUCCESS"),
    PASSWORD_RECOVER_ERROR("PASSWORD_RECOVER_ERROR"),

    // Shop section
    SHOP_CREATION_SUCCESS("SHOP_CREATION_SUCCESS"),
    SHOP_CREATION_ERROR("SHOP_CREATION_ERROR"),
    SHOP_NOT_FOUND("SHOP_NOT_FOUND"),
    SHOP_DELETE_SUCCESS("SHOP_DELETE_SUCCESS"),
    SHOP_DELETE_ERROR("SHOP_DELETE_ERROR"),

    // Item section
    ITEM_CREATION_SUCCESS("ITEM_CREATION_SUCCESS"),
    ITEM_CREATION_ERROR("ITEM_CREATION_ERROR"),
    ITEM_NOT_FOUND("ITEM_NOT_FOUND"),
    ITEM_DELETE_SUCCESS("ITEM_DELETE_SUCCESS"),
    ITEM_DELETE_ERROR("ITEM_DELETE_ERROR"),
    ITEM_UPDATE_SUCCESS("ITEM_DELETE_SUCCESS"),
    ITEM_UPDATE_ERROR("ITEM_DELETE_ERROR"),

    ;



    private final String message;

    Message(String message){
        this.message = message;
    }

    public String getValue(){
        return this.message;
    }
}